package ch.gabrieltransport.auftragverwaltung.ui.adminViews;

import ch.gabrieltransport.auftragverwaltung.dal.LogDAO;
import ch.gabrieltransport.auftragverwaltung.entities.Log;
import ch.gabrieltransport.auftragverwaltung.entities.Log_;
import ch.gabrieltransport.auftragverwaltung.entities.User_;
import com.vaadin.navigator.ViewChangeListener;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.xdev.dal.DAOs;
import com.xdev.ui.XdevButton;
import com.xdev.ui.XdevGridLayout;
import com.xdev.ui.XdevView;
import com.xdev.ui.entitycomponent.table.XdevTable;
import com.xdev.ui.navigation.Navigation;
import com.xdev.ui.util.NestedProperty;

public class logView extends XdevView {

	/**
	 * 
	 */
	public logView() {
		super();
		this.initUI();
	}

	@Override
	public void enter(ViewChangeListener.ViewChangeEvent event) {
		super.enter(event);
	
	}

	/**
	 * Event handler delegate method for the {@link XdevButton} {@link #btnReturn}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void btnReturn_buttonClick(Button.ClickEvent event) {
	Navigation.to("home").navigate();
	}

	/*
	 * WARNING: Do NOT edit!<br>The content of this method is always regenerated by
	 * the UI designer.
	 */
	// <generated-code name="initUI">
	private void initUI() {
		this.gridLayout = new XdevGridLayout();
		this.gridLayout2 = new XdevGridLayout();
		this.btnReturn = new XdevButton();
		this.table2 = new XdevTable<>();
	
		this.btnReturn.setCaption("Auftragsverwaltung");
		this.table2.setPageLength(50);
		this.table2.setSortAscending(false);
		this.table2.setContainerDataSource(Log.class, DAOs.get(LogDAO.class).findLog());
		this.table2.setVisibleColumns(Log_.logtime.getName(), Log_.logmessage.getName(), Log_.user.getName());
		this.table2.setColumnHeader("logtime", "Logzeit");
		this.table2.setColumnHeader("logmessage", "Nachricht");
		this.table2.setColumnHeader("user", "Benutzername");
	
		this.gridLayout2.setColumns(1);
		this.gridLayout2.setRows(2);
		this.btnReturn.setSizeUndefined();
		this.gridLayout2.addComponent(this.btnReturn, 0, 0);
		this.table2.setSizeFull();
		this.gridLayout2.addComponent(this.table2, 0, 1);
		this.gridLayout2.setColumnExpandRatio(0, 100.0F);
		this.gridLayout2.setRowExpandRatio(1, 100.0F);
		this.gridLayout.setColumns(1);
		this.gridLayout.setRows(1);
		this.gridLayout2.setSizeFull();
		this.gridLayout.addComponent(this.gridLayout2, 0, 0);
		this.gridLayout.setColumnExpandRatio(0, 10.0F);
		this.gridLayout.setRowExpandRatio(0, 10.0F);
		this.gridLayout.setSizeFull();
		this.setContent(this.gridLayout);
		this.setSizeFull();
	
		this.btnReturn.addClickListener(event -> this.btnReturn_buttonClick(event));
	} // </generated-code>

	// <generated-code name="variables">
	private XdevButton btnReturn;
	private XdevTable<Log> table2;
	private XdevGridLayout gridLayout, gridLayout2;
	// </generated-code>

}
