package ch.gabrieltransport.auftragverwaltung.ui.fahrerViews;

import ch.gabrieltransport.auftragverwaltung.business.refresher.Broadcaster;
import ch.gabrieltransport.auftragverwaltung.entities.Fahrer;
import ch.gabrieltransport.auftragverwaltung.entities.Fahrer_;
import ch.gabrieltransport.auftragverwaltung.entities.Fahrzeug;
import ch.gabrieltransport.auftragverwaltung.ui.fahrzeugViews.FahrzeugDetail.Callback;
import com.vaadin.event.FieldEvents;
import com.vaadin.shared.ui.MarginInfo;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Window;
import com.xdev.ui.XdevButton;
import com.xdev.ui.XdevFieldGroup;
import com.xdev.ui.XdevGridLayout;
import com.xdev.ui.XdevHorizontalLayout;
import com.xdev.ui.XdevLabel;
import com.xdev.ui.XdevTextField;
import com.xdev.ui.XdevView;

public class DriverDetail extends XdevView {

	
	/**
	 * 
	 */
	public DriverDetail(Callback callback) {
		super();
		this.initUI();
		this.callback = callback;
		this.fieldGroup.setItemDataSource(new Fahrer());
	}
	
	public DriverDetail(Fahrer driver, Callback callback) {
		super();
		this.initUI();
		this.callback = callback;
		this.fieldGroup.setItemDataSource(driver);
	}
	
	public static class Callback{
		public void onDialogResult(Fahrer result){}
	}
	private Callback callback;

	/**
	 * Event handler delegate method for the {@link XdevButton} {@link #cmdReturn}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void cmdReturn_buttonClick(Button.ClickEvent event) {
		((Window)this.getParent()).close();
	}

	/**
	 * Event handler delegate method for the {@link XdevButton} {@link #cmdSave}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void cmdSave_buttonClick(Button.ClickEvent event) {
		callback.onDialogResult(this.fieldGroup.save());
		Broadcaster.broadcast("DRIVER");
		((Window)this.getParent()).close();
	}

	/**
	 * Event handler delegate method for the {@link XdevTextField}
	 * {@link #txtVorname}.
	 *
	 * @see FieldEvents.TextChangeListener#textChange(FieldEvents.TextChangeEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void txtVorname_textChange(FieldEvents.TextChangeEvent event) {
		txtName.setValue(txtNachname.getValue() + ", " + txtVorname.getValue());
	}

	/**
	 * Event handler delegate method for the {@link XdevTextField}
	 * {@link #txtNachname}.
	 *
	 * @see FieldEvents.TextChangeListener#textChange(FieldEvents.TextChangeEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void txtNachname_textChange(FieldEvents.TextChangeEvent event) {
		txtName.setValue(txtNachname.getValue() + ", " + txtVorname.getValue());
	}

	/*
	 * WARNING: Do NOT edit!<br>The content of this method is always regenerated by
	 * the UI designer.
	 */
	// <generated-code name="initUI">
	private void initUI() {
		this.gridLayout = new XdevGridLayout();
		this.form = new XdevGridLayout();
		this.lblNachname = new XdevLabel();
		this.txtNachname = new XdevTextField();
		this.lblVorname = new XdevLabel();
		this.txtVorname = new XdevTextField();
		this.lblName = new XdevLabel();
		this.txtName = new XdevTextField();
		this.lblTelefon = new XdevLabel();
		this.txtTelefon = new XdevTextField();
		this.horizontalLayout = new XdevHorizontalLayout();
		this.cmdReturn = new XdevButton();
		this.cmdSave = new XdevButton();
		this.fieldGroup = new XdevFieldGroup<>(Fahrer.class);
	
		this.lblNachname.setValue("Nachname");
		this.txtNachname.setColumns(5);
		this.txtNachname.setTabIndex(1);
		this.lblVorname.setValue("Vorname");
		this.txtVorname.setColumns(5);
		this.txtVorname.setTabIndex(2);
		this.lblName.setValue("Name");
		this.txtName.setColumns(5);
		this.txtName.setTabIndex(3);
		this.lblTelefon.setValue("Telefon");
		this.txtTelefon.setColumns(5);
		this.txtTelefon.setTabIndex(4);
		this.horizontalLayout.setMargin(new MarginInfo(false));
		this.cmdReturn.setCaption("Abbrechen");
		this.cmdReturn.setTabIndex(6);
		this.cmdSave.setCaption("Speichern");
		this.cmdSave.setTabIndex(7);
		this.fieldGroup.bind(this.txtNachname, Fahrer_.nachname.getName());
		this.fieldGroup.bind(this.txtVorname, Fahrer_.vorname.getName());
		this.fieldGroup.bind(this.txtName, Fahrer_.name.getName());
		this.fieldGroup.bind(this.txtTelefon, Fahrer_.telefon.getName());
	
		this.cmdReturn.setSizeUndefined();
		this.horizontalLayout.addComponent(this.cmdReturn);
		this.horizontalLayout.setComponentAlignment(this.cmdReturn, Alignment.MIDDLE_LEFT);
		this.cmdSave.setSizeUndefined();
		this.horizontalLayout.addComponent(this.cmdSave);
		this.horizontalLayout.setComponentAlignment(this.cmdSave, Alignment.MIDDLE_LEFT);
		this.form.setColumns(2);
		this.form.setRows(5);
		this.lblNachname.setSizeUndefined();
		this.form.addComponent(this.lblNachname, 0, 0);
		this.txtNachname.setSizeUndefined();
		this.form.addComponent(this.txtNachname, 1, 0);
		this.lblVorname.setSizeUndefined();
		this.form.addComponent(this.lblVorname, 0, 1);
		this.txtVorname.setSizeUndefined();
		this.form.addComponent(this.txtVorname, 1, 1);
		this.lblName.setSizeUndefined();
		this.form.addComponent(this.lblName, 0, 2);
		this.txtName.setSizeUndefined();
		this.form.addComponent(this.txtName, 1, 2);
		this.lblTelefon.setSizeUndefined();
		this.form.addComponent(this.lblTelefon, 0, 3);
		this.txtTelefon.setSizeUndefined();
		this.form.addComponent(this.txtTelefon, 1, 3);
		this.horizontalLayout.setSizeUndefined();
		this.form.addComponent(this.horizontalLayout, 0, 4, 1, 4);
		this.form.setComponentAlignment(this.horizontalLayout, Alignment.TOP_RIGHT);
		this.gridLayout.setColumns(2);
		this.gridLayout.setRows(2);
		this.form.setSizeUndefined();
		this.gridLayout.addComponent(this.form, 0, 0);
		final CustomComponent gridLayout_hSpacer = new CustomComponent();
		gridLayout_hSpacer.setSizeFull();
		this.gridLayout.addComponent(gridLayout_hSpacer, 1, 0, 1, 0);
		this.gridLayout.setColumnExpandRatio(1, 1.0F);
		final CustomComponent gridLayout_vSpacer = new CustomComponent();
		gridLayout_vSpacer.setSizeFull();
		this.gridLayout.addComponent(gridLayout_vSpacer, 0, 1, 0, 1);
		this.gridLayout.setRowExpandRatio(1, 1.0F);
		this.gridLayout.setSizeFull();
		this.setContent(this.gridLayout);
		this.setSizeFull();
	
		this.txtNachname.addTextChangeListener(event -> this.txtNachname_textChange(event));
		this.txtVorname.addTextChangeListener(event -> this.txtVorname_textChange(event));
		this.cmdReturn.addClickListener(event -> this.cmdReturn_buttonClick(event));
		this.cmdSave.addClickListener(event -> this.cmdSave_buttonClick(event));
	} // </generated-code>

	// <generated-code name="variables">
	private XdevLabel lblNachname, lblVorname, lblName, lblTelefon;
	private XdevButton cmdReturn, cmdSave;
	private XdevHorizontalLayout horizontalLayout;
	private XdevGridLayout gridLayout, form;
	private XdevTextField txtNachname, txtVorname, txtName, txtTelefon;
	private XdevFieldGroup<Fahrer> fieldGroup;
	// </generated-code>

}
