package ch.gabrieltransport.auftragverwaltung.ui;

import ch.gabrieltransport.auftragverwaltung.entities.Auftrag_;
import ch.gabrieltransport.auftragverwaltung.entities.Fahrerauftrag;
import ch.gabrieltransport.auftragverwaltung.entities.Fahrerauftrag_;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.xdev.ui.XdevGridLayout;
import com.xdev.ui.XdevHorizontalLayout;
import com.xdev.ui.XdevPopupDateField;
import com.xdev.ui.XdevView;
import com.xdev.ui.entitycomponent.combobox.XdevComboBox;
import com.xdev.ui.entitycomponent.table.XdevTable;
import com.xdev.ui.util.NestedProperty;

public class driverDetail extends XdevView {

	/**
	 * 
	 */
	public driverDetail() {
		super();
		this.initUI();
	}

	/*
	 * WARNING: Do NOT edit!<br>The content of this method is always regenerated by
	 * the UI designer.
	 */
	// <generated-code name="initUI">
	private void initUI() {
		this.gridLayout = new XdevGridLayout();
		this.horizontalLayout = new XdevHorizontalLayout();
		this.comboBox = new XdevComboBox<>();
		this.popupDateField = new XdevPopupDateField();
		this.popupDateField2 = new XdevPopupDateField();
		this.table = new XdevTable<>();
	
		this.table.setContainerDataSource(Fahrerauftrag.class, false,
				NestedProperty.of(Fahrerauftrag_.auftrag, Auftrag_.bezeichung));
		this.table.setVisibleColumns(NestedProperty.path(Fahrerauftrag_.auftrag, Auftrag_.bezeichung),
				Fahrerauftrag_.vonDatum.getName(), Fahrerauftrag_.bisDatum.getName());
	
		this.comboBox.setSizeUndefined();
		this.horizontalLayout.addComponent(this.comboBox);
		this.popupDateField.setSizeUndefined();
		this.horizontalLayout.addComponent(this.popupDateField);
		this.horizontalLayout.setComponentAlignment(this.popupDateField, Alignment.MIDDLE_CENTER);
		this.popupDateField2.setSizeUndefined();
		this.horizontalLayout.addComponent(this.popupDateField2);
		this.horizontalLayout.setComponentAlignment(this.popupDateField2, Alignment.MIDDLE_CENTER);
		final CustomComponent horizontalLayout_spacer = new CustomComponent();
		horizontalLayout_spacer.setSizeFull();
		this.horizontalLayout.addComponent(horizontalLayout_spacer);
		this.horizontalLayout.setExpandRatio(horizontalLayout_spacer, 1.0F);
		this.gridLayout.setColumns(1);
		this.gridLayout.setRows(2);
		this.horizontalLayout.setWidth(100, Unit.PERCENTAGE);
		this.horizontalLayout.setHeight(100, Unit.PIXELS);
		this.gridLayout.addComponent(this.horizontalLayout, 0, 0);
		this.table.setSizeFull();
		this.gridLayout.addComponent(this.table, 0, 1);
		this.gridLayout.setRowExpandRatio(1, 100.0F);
		this.gridLayout.setSizeFull();
		this.setContent(this.gridLayout);
		this.setSizeFull();
	} // </generated-code>

	// <generated-code name="variables">
	private XdevTable<Fahrerauftrag> table;
	private XdevHorizontalLayout horizontalLayout;
	private XdevPopupDateField popupDateField, popupDateField2;
	private XdevComboBox<?> comboBox;
	private XdevGridLayout gridLayout;
	// </generated-code>

}
