package ch.gabrieltransport.auftragverwaltung.ui;

import ch.gabrieltransport.auftragverwaltung.dal.UserDAO;
import ch.gabrieltransport.auftragverwaltung.entities.User;
import ch.gabrieltransport.auftragverwaltung.entities.User_;
import com.vaadin.navigator.ViewChangeListener;
import com.vaadin.shared.ui.MarginInfo;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Notification;
import com.vaadin.ui.Notification.Type;
import com.xdev.security.authentication.jpa.HashStrategy;
import com.xdev.security.authentication.ui.Authentication;
import com.xdev.ui.XdevButton;
import com.xdev.ui.XdevFieldGroup;
import com.xdev.ui.XdevGridLayout;
import com.xdev.ui.XdevHorizontalLayout;
import com.xdev.ui.XdevLabel;
import com.xdev.ui.XdevPasswordField;
import com.xdev.ui.XdevTextField;
import com.xdev.ui.XdevView;
import com.xdev.ui.navigation.Navigation;

public class userDetail extends XdevView {

	private UserDAO userdao = new UserDAO();
	private User currentUser;
	/**
	 * 
	 */
	public userDetail() {
		super();
		this.initUI();
		currentUser = userdao.findCurrentUser(Authentication.getUser().name()).get(0);
		this.fieldGroup.setItemDataSource(currentUser);
	}

	@Override
	public void enter(ViewChangeListener.ViewChangeEvent event) {
		super.enter(event);
	
	}

	/**
	 * Event handler delegate method for the {@link XdevButton} {@link #cmdSave}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void cmdSave_buttonClick(Button.ClickEvent event) {
		if(txtPassword.getValue().equals(txtPassword2.getValue())){
			if(!txtPassword.getValue().equals("")){
				byte[] password = new HashStrategy.SHA2().hashPassword(txtPassword.getValue().getBytes());
		
				currentUser.setUsername(txtUsername.getValue());
				currentUser.setPassword(password);
				  
				//Über die UserDAO (Data Access Object) die Werte in die Datenbank speichern.
				new UserDAO().merge(currentUser);
		
				//Danach die FieldGroup wieder leeren.
				this.fieldGroup.clear();
				Navigation.to("home").navigate();
			}else{
				Notification.show("Passwort darf nicht leer sein", Type.WARNING_MESSAGE);
			}
		}else{
			Notification.show("Passwörter stimmen nicht überein", Type.WARNING_MESSAGE);
		}
	}

	/**
	 * Event handler delegate method for the {@link XdevButton} {@link #btnReturn}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void btnReturn_buttonClick(Button.ClickEvent event) {
		Navigation.to("home").navigate();
	}

	/*
	 * WARNING: Do NOT edit!<br>The content of this method is always regenerated by
	 * the UI designer.
	 */
	// <generated-code name="initUI">
	private void initUI() {
		this.gridLayout = new XdevGridLayout();
		this.form = new XdevGridLayout();
		this.horizontalLayout2 = new XdevHorizontalLayout();
		this.btnReturn = new XdevButton();
		this.cmdSave = new XdevButton();
		this.lblUsername = new XdevLabel();
		this.txtUsername = new XdevTextField();
		this.lblPassword = new XdevLabel();
		this.txtPassword = new XdevPasswordField();
		this.txtConfirmPassword = new XdevLabel();
		this.txtPassword2 = new XdevPasswordField();
		this.fieldGroup = new XdevFieldGroup<>(User.class);
	
		this.horizontalLayout2.setMargin(new MarginInfo(true, false, true, false));
		this.btnReturn.setCaption("Abbrechen");
		this.cmdSave.setCaption("Save");
		this.lblUsername.setValue("Username");
		this.txtUsername.setTabIndex(1);
		this.txtUsername.setReadOnly(true);
		this.lblPassword.setValue("Password");
		this.txtPassword.setTabIndex(2);
		this.txtConfirmPassword.setValue("Password bestätigen");
		this.fieldGroup.bind(this.txtUsername, User_.username.getName());
	
		this.btnReturn.setSizeUndefined();
		this.horizontalLayout2.addComponent(this.btnReturn);
		this.cmdSave.setSizeUndefined();
		this.horizontalLayout2.addComponent(this.cmdSave);
		this.horizontalLayout2.setComponentAlignment(this.cmdSave, Alignment.TOP_CENTER);
		final CustomComponent horizontalLayout2_spacer = new CustomComponent();
		horizontalLayout2_spacer.setSizeFull();
		this.horizontalLayout2.addComponent(horizontalLayout2_spacer);
		this.horizontalLayout2.setExpandRatio(horizontalLayout2_spacer, 1.0F);
		this.form.setColumns(2);
		this.form.setRows(4);
		this.horizontalLayout2.setWidth(100, Unit.PERCENTAGE);
		this.horizontalLayout2.setHeight(50, Unit.PIXELS);
		this.form.addComponent(this.horizontalLayout2, 1, 3);
		this.lblUsername.setSizeUndefined();
		this.form.addComponent(this.lblUsername, 0, 0);
		this.txtUsername.setWidth(100, Unit.PERCENTAGE);
		this.txtUsername.setHeight(-1, Unit.PIXELS);
		this.form.addComponent(this.txtUsername, 1, 0);
		this.lblPassword.setSizeUndefined();
		this.form.addComponent(this.lblPassword, 0, 1);
		this.txtPassword.setWidth(100, Unit.PERCENTAGE);
		this.txtPassword.setHeight(-1, Unit.PIXELS);
		this.form.addComponent(this.txtPassword, 1, 1);
		this.txtConfirmPassword.setSizeUndefined();
		this.form.addComponent(this.txtConfirmPassword, 0, 2);
		this.txtPassword2.setWidth(100, Unit.PERCENTAGE);
		this.txtPassword2.setHeight(-1, Unit.PIXELS);
		this.form.addComponent(this.txtPassword2, 1, 2);
		this.form.setColumnExpandRatio(0, 10.0F);
		this.form.setColumnExpandRatio(1, 30.0F);
		this.gridLayout.setColumns(1);
		this.gridLayout.setRows(2);
		this.form.setWidth(500, Unit.PIXELS);
		this.form.setHeight(-1, Unit.PIXELS);
		this.gridLayout.addComponent(this.form, 0, 0);
		this.gridLayout.setColumnExpandRatio(0, 10.0F);
		final CustomComponent gridLayout_vSpacer = new CustomComponent();
		gridLayout_vSpacer.setSizeFull();
		this.gridLayout.addComponent(gridLayout_vSpacer, 0, 1, 0, 1);
		this.gridLayout.setRowExpandRatio(1, 1.0F);
		this.gridLayout.setSizeFull();
		this.setContent(this.gridLayout);
		this.setSizeFull();
	
		this.btnReturn.addClickListener(event -> this.btnReturn_buttonClick(event));
		this.cmdSave.addClickListener(event -> this.cmdSave_buttonClick(event));
	} // </generated-code>

	// <generated-code name="variables">
	private XdevButton btnReturn, cmdSave;
	private XdevLabel lblUsername, lblPassword, txtConfirmPassword;
	private XdevHorizontalLayout horizontalLayout2;
	private XdevPasswordField txtPassword, txtPassword2;
	private XdevGridLayout gridLayout, form;
	private XdevTextField txtUsername;
	private XdevFieldGroup<User> fieldGroup;
	// </generated-code>

}
