
package ch.gabrieltransport.auftragverwaltung.dal;

import com.xdev.dal.JPADAO;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Root;
import ch.gabrieltransport.auftragverwaltung.entities.Fahrzeug;
import ch.gabrieltransport.auftragverwaltung.entities.Fahrzeug_;

/**
 * Home object for domain model class Fahrzeug.
 * 
 * @see Fahrzeug
 */
public class FahrzeugDAO extends JPADAO<Fahrzeug, Integer> {
	public FahrzeugDAO() {
		super(Fahrzeug.class);
	}

	/**
	 * @queryMethod Do not edit, method is generated by editor!
	 */
	public List<Fahrzeug> findAllOrderNumber() {
		EntityManager entityManager = em();
	
		CriteriaBuilder criteriaBuilder = entityManager.getCriteriaBuilder();
	
		CriteriaQuery<Fahrzeug> criteriaQuery = criteriaBuilder.createQuery(Fahrzeug.class);
	
		Root<Fahrzeug> root = criteriaQuery.from(Fahrzeug.class);
	
		criteriaQuery.orderBy(criteriaBuilder.asc(root.get(Fahrzeug_.nummer)));
	
		TypedQuery<Fahrzeug> query = entityManager.createQuery(criteriaQuery);
		return query.getResultList();
	}
}