
package ch.gabrieltransport.auftragverwaltung.dal;

import ch.gabrieltransport.auftragverwaltung.entities.Log;
import ch.gabrieltransport.auftragverwaltung.entities.Log_;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Root;
import com.xdev.dal.JPADAO;

/**
 * Home object for domain model class Log.
 * 
 * @see Log
 */
public class LogDAO extends JPADAO<Log, Integer> {
	
	@PersistenceContext
	EntityManager entityManager;
	
	public LogDAO() {
		super(Log.class);
	}
	

	/**
	 * @queryMethod Do not edit, method is generated by editor!
	 */
	public List<Log> findLog() {
		EntityManager entityManager = em();
	
		CriteriaBuilder criteriaBuilder = entityManager.getCriteriaBuilder();
	
		CriteriaQuery<Log> criteriaQuery = criteriaBuilder.createQuery(Log.class);
	
		Root<Log> root = criteriaQuery.from(Log.class);
	
		criteriaQuery.orderBy(criteriaBuilder.desc(root.get(Log_.logtime)));
	
		TypedQuery<Log> query = entityManager.createQuery(criteriaQuery);
		query.setMaxResults(50);
		return query.getResultList();
	}
}