
package ch.gabrieltransport.auftragverwaltung.dal;

import com.xdev.dal.JPADAO;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.ParameterExpression;
import javax.persistence.criteria.Root;
import ch.gabrieltransport.auftragverwaltung.entities.User;
import ch.gabrieltransport.auftragverwaltung.entities.User_;

/**
 * Home object for domain model class User.
 * 
 * @see User
 */
public class UserDAO extends JPADAO<User, Integer> {
	public UserDAO() {
		super(User.class);
	}

	/**
	 * @queryMethod Do not edit, method is generated by editor!
	 */
	public List<User> findCurrentUser(String username) {
		EntityManager entityManager = em();
	
		CriteriaBuilder criteriaBuilder = entityManager.getCriteriaBuilder();
	
		ParameterExpression<String> usernameParameter = criteriaBuilder.parameter(String.class, "username");
	
		CriteriaQuery<User> criteriaQuery = criteriaBuilder.createQuery(User.class);
	
		Root<User> root = criteriaQuery.from(User.class);
	
		criteriaQuery.where(criteriaBuilder.equal(root.get(User_.username), usernameParameter));
	
		TypedQuery<User> query = entityManager.createQuery(criteriaQuery);
		query.setParameter(usernameParameter, username);
		query.setMaxResults(1);
		return query.getResultList();
	}
}